
#!/bin/bash

# Login to azure container registry
echo docker login $WERCKER_AZURE_CONTAINER_REGISTRY_PUSH_REGISTRY_URL -u $WERCKER_AZURE_CONTAINER_REGISTRY_PUSH_USERNAME -p $WERCKER_AZURE_CONTAINER_REGISTRY_PUSH_PASSWORD

# Push the container to Azure container registry
echo docker push $WERCKER_AZURE_CONTAINER_REGISTRY_PUSH_REGISTRY_URL/$WERCKER_AZURE_CONTAINER_REGISTRY_PUSH_REPOSITORY